# x265guiEx
# continuous integration settings

image: Visual Studio 2015

platform: Win32
configuration: Release
skip_non_tags: true

branches:
  only:
    - master

init:
  - ps: Set-WinSystemLocale ja-JP
  - ps: Start-Sleep -s 5
  - ps: Restart-Computer
  - git config --global core.autocrlf input

install:
  - git submodule update --init --recursive
  
before_build:
  - ps: |
      $version = $null
      if (Test-Path Env:APPVEYOR_REPO_TAG_NAME)
      {
          $version = (Get-Item Env:APPVEYOR_REPO_TAG_NAME).Value
      }
      
      if ([string]::IsNullOrEmpty($version))
      {
          $version = $env:APPVEYOR_BUILD_VERSION + '_Alpha'
      }
      $env:BUILD_VERSION=$version

  - echo %BUILD_VERSION%
  - appveyor UpdateBuild -Version "%BUILD_VERSION%"

build:
  parallel: true
  project: x265guiEx.sln

after_build:
  - mkdir auo
  - copy Release\x265guiEx.auo auo\x265guiEx.auo
  - copy Release\x265guiEx.ini auo\x265guiEx.ini
  - 7z a -mx9 x265guiEx_%BUILD_VERSION%.7z auo

artifacts:
  - path: x265guiEx_%BUILD_VERSION%.7z
    name: x265guiEx_%BUILD_VERSION%

deploy:
  provider: GitHub
  auth_token:
    secure: IDRwZWN1uQaTxb64SQnTDNJR5KPtCFPL3Mln9GrdZ7TSiyec/o1KXpOuh/50ZO5A
  artifact: x265guiEx_%BUILD_VERSION%_%PLATFORM%
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
